
INSERT INTO genero (nome) VALUES ('Acao');
INSERT INTO genero (nome) VALUES ('Animacao');
INSERT INTO genero (nome) VALUES ('Aventura');
INSERT INTO genero (nome) VALUES ('Cinema de arte');
INSERT INTO genero (nome) VALUES ('Chanchada');
INSERT INTO genero (nome) VALUES ('Cinema catastrofe');
INSERT INTO genero (nome) VALUES ('Comedia');
INSERT INTO genero (nome) VALUES ('Comedia romantica');
INSERT INTO genero (nome) VALUES ('Comedia dramatica');
INSERT INTO genero (nome) VALUES ('Comedia de acao');
INSERT INTO genero (nome) VALUES ('Cult');
INSERT INTO genero (nome) VALUES ('Danca');
INSERT INTO genero (nome) VALUES ('Documentario');
INSERT INTO genero (nome) VALUES ('Docuficcao');
INSERT INTO genero (nome) VALUES ('Drama');
INSERT INTO genero (nome) VALUES ('Espionagem');
INSERT INTO genero (nome) VALUES ('Ficcao cientifica');
INSERT INTO genero (nome) VALUES ('Musical');
INSERT INTO genero (nome) VALUES ('Policial');
INSERT INTO genero (nome) VALUES ('Romance');
INSERT INTO genero (nome) VALUES ('Suspense');
INSERT INTO genero (nome) VALUES ('Terror');

INSERT INTO produtora (nome) VALUES ('AMC');
INSERT INTO produtora (nome) VALUES ('HBO');
INSERT INTO produtora (nome) VALUES ('CBS');
INSERT INTO produtora (nome) VALUES ('BBC');
INSERT INTO produtora (nome) VALUES ('Sony');
INSERT INTO produtora (nome) VALUES ('Fox');
INSERT INTO produtora (nome) VALUES ('Disney');
INSERT INTO produtora (nome) VALUES ('NBC Universal');
INSERT INTO produtora (nome) VALUES ('Warner Bros');
INSERT INTO produtora (nome) VALUES ('ABC');
INSERT INTO produtora (nome) VALUES ('Netflix');
INSERT INTO produtora (nome) VALUES ('Amazon');
INSERT INTO produtora (nome) VALUES ('FX Productions');
INSERT INTO produtora (nome) VALUES ('Paramount');

INSERT INTO serie (nome, resumo, data_estreia, data_encerramento, nota, genero_id, produtora_id, imagem) VALUES ('Game of Trones', 'Nine noble families fight for control over the mythical lands of Westeros, while an ancient enemy returns after being dormant for thousands of years.','2011-04-17', null, 95.00, 3, 2, '1.jpg');
INSERT INTO serie (nome, resumo, data_estreia, data_encerramento, nota, genero_id, produtora_id, imagem) VALUES ('Breaking Bad', 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family`s future.','2008-01-20', '2013-09-29', 95.00, 15, 1, '2.jpg');
INSERT INTO serie (nome, resumo, data_estreia, data_encerramento, nota, genero_id, produtora_id, imagem) VALUES ('The Walking Dead', 'Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins, and must lead a group of survivors to stay alive.','2010-10-31', null, 84.00, 1, 1, '3.jpg');
INSERT INTO serie (nome, resumo, data_estreia, data_encerramento, nota, genero_id, produtora_id, imagem) VALUES ('Dexter', 'By day, mild-mannered Dexter is a blood-spatter analyst for the Miami police. But at night, he is a serial killer who only targets other murderers.','2006-10-01', '2013-09-22', 87.00, 1, 1, '4.jpg');
INSERT INTO serie (nome, resumo, data_estreia, data_encerramento, nota, genero_id, produtora_id, imagem) VALUES ('Lost', 'The survivors of a plane crash are forced to work together in order to survive on a seemingly deserted tropical island.','2004-09-22', '2010-05-23', 84.00, 1, 1, '5.jpg');
INSERT INTO serie (nome, resumo, data_estreia, data_encerramento, nota, genero_id, produtora_id, imagem) VALUES ('The Big Bang Theory', 'A woman who moves into an apartment across the hall from two brilliant but socially awkward physicists shows them how little they know about life outside of the laboratory.','2007-09-24', null, 82.00, 1, 1, '6.jpg');
INSERT INTO serie (nome, resumo, data_estreia, data_encerramento, nota, genero_id, produtora_id, imagem) VALUES ('Two and a Half Men', 'A hedonistic jingle writer`s free-wheeling life comes to an abrupt halt when his brother and 10-year-old nephew move into his beach-front house.','2003-09-22', '2015-02-19', 71.00, 1, 1, '7.jpg');
INSERT INTO serie (nome, resumo, data_estreia, data_encerramento, nota, genero_id, produtora_id, imagem) VALUES ('South Park', 'Follows the misadventures of four irreverent grade-schoolers in the quiet, dysfunctional town of South Park, Colorado.','1997-08-13', null, 87.00, 1, 1, '8.jpg');
INSERT INTO serie (nome, resumo, data_estreia, data_encerramento, nota, genero_id, produtora_id, imagem) VALUES ('The Simpsons', 'The satiric adventures of a working-class family in the misfit city of Springfield.','1989-12-17', null, 87.00, 1, 1, '9.jpg');
INSERT INTO serie (nome, resumo, data_estreia, data_encerramento, nota, genero_id, produtora_id, imagem) VALUES ('Family Guy', 'In a wacky Rhode Island town, a dysfunctional family strive to cope with everyday life as they are thrown from one crazy scenario to another.','1999-01-31', null, 82.00, 1, 1, '10.jpg');
INSERT INTO serie (nome, resumo, data_estreia, data_encerramento, nota, genero_id, produtora_id, imagem) VALUES ('The X Files', 'Two FBI agents, Fox Mulder the believer and Dana Scully the skeptic, investigate the strange and unexplained, while hidden forces work to impede their efforts.','1993-09-10', null, 87.00, 1, 1, '11.jpg');
INSERT INTO serie (nome, resumo, data_estreia, data_encerramento, nota, genero_id, produtora_id, imagem) VALUES ('Vikings', 'The world of the Vikings is brought to life through the journey of Ragnar Lothbrok, the first Viking to emerge from Norse legend and onto the pages of history - a man on the edge of myth.','2016-06-13', null, 86.00, 1, 1, '12.jpg');
